"""PowerPoint utilities: reading, creating .pptx files, and smart content-based conversion
to/from Word documents and PDFs.

This module features a Semantic Layout Engine: when converting from Word or text,
it automatically detects Headings to create Slide Titles, formats normal text as 
bullet points, and dynamically snaps images into professional slide layouts.
"""
import os
import random
import tempfile
import urllib.request
from pptx import Presentation
from pptx.util import Inches, Pt

CLOUD_THEMES = [
    "https://raw.githubusercontent.com/Samuel-Peprah-cmd/quicktools/main/assets/themes/modern_blue.pptx",
    "https://raw.githubusercontent.com/Samuel-Peprah-cmd/quicktools/main/assets/themes/dark_minimal.pptx",
    "https://raw.githubusercontent.com/Samuel-Peprah-cmd/quicktools/main/assets/themes/creative_orange.pptx"
]

def _get_template_path(template_target: str | None) -> str | None:
    """Internal helper: Resolves a template file, a local directory, or fetches a cloud theme."""
    if not template_target:
        return None
        
    # --- NEW: Cloud Fetching ---
    if template_target.lower() == "random_cloud":
        print("Fetching a random theme from the cloud...")
        url = random.choice(CLOUD_THEMES)
        try:
            # Create a temporary file that deletes itself when the script finishes
            temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pptx")
            urllib.request.urlretrieve(url, temp_file.name)
            return temp_file.name
        except Exception as e:
            print(f"Warning: Could not fetch cloud theme ({e}). Falling back to blank template.")
            return None

    # --- Local File/Folder Logic ---
    if os.path.isfile(template_target) and template_target.endswith('.pptx'):
        return template_target
        
    if os.path.isdir(template_target):
        templates = [os.path.join(template_target, f) for f in os.listdir(template_target) if f.endswith('.pptx')]
        if templates:
            return random.choice(templates)
            
    return None

def read_pptx_text(path: str) -> str:
    """Extract all text from every slide in a .pptx file."""
    prs = Presentation(path)
    lines = []
    for slide in prs.slides:
        for shape in slide.shapes:
            if shape.has_text_frame:
                for paragraph in shape.text_frame.paragraphs:
                    text = "".join(run.text for run in paragraph.runs)
                    if text:
                        lines.append(text)
    return "\n".join(lines)


def get_pptx_slide_count(path: str) -> int:
    """Return the number of slides in a .pptx file."""
    return len(Presentation(path).slides)


def create_smart_pptx(slide_data: list[dict], output_path: str, template_target: str | None = None) -> None:
    """
    Creates a formatted PowerPoint presentation from structured data.
    slide_data format: [{"title": "Slide 1", "content": ["Point 1", "Point 2"], "image": "path.jpg"}]
    
    If template_target is a directory, a random .pptx theme from that directory is applied.
    """
    theme = _get_template_path(template_target)
    prs = Presentation(theme) if theme else Presentation()

    # Standard Layout indices: 0 = Title Slide, 1 = Title & Content, 8 = Picture with Caption
    title_slide_layout = prs.slide_layouts[0]
    
    # Fallbacks in case the custom template is structured unusually
    try:
        content_slide_layout = prs.slide_layouts[1]
    except IndexError:
        content_slide_layout = prs.slide_layouts[0]

    for i, slide_dict in enumerate(slide_data):
        title = slide_dict.get("title", "Untitled Slide")
        content = slide_dict.get("content", [])
        image_path = slide_dict.get("image", None)

        # Use Title Slide layout for the very first slide if it has no bullets
        if i == 0 and not content and not image_path:
            slide = prs.slides.add_slide(title_slide_layout)
            if slide.shapes.title:
                slide.shapes.title.text = title
            if len(slide.placeholders) > 1:
                slide.placeholders[1].text = "Generated by quicktools"
            continue

        # Create a standard slide
        slide = prs.slides.add_slide(content_slide_layout)
        
        # Set Title
        if slide.shapes.title:
            slide.shapes.title.text = title
        
        # Set Bullet Points
        if len(slide.placeholders) > 1:
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            
            for idx, point in enumerate(content):
                p = tf.paragraphs[0] if idx == 0 else tf.add_paragraph()
                p.text = point
                p.font.size = Pt(20)

            # Smart Image Placement Strategy
            if image_path and os.path.exists(image_path):
                # Shrink the text box to make room for the image on the right
                body_shape.width = Inches(5)
                
                # Snap image to the right side of a standard 10x7.5 widescreen slide
                left_position = Inches(5.5)
                top_position = Inches(2)
                image_height = Inches(4.5)
                
                slide.shapes.add_picture(image_path, left_position, top_position, height=image_height)

    prs.save(output_path)


def create_pptx_from_text(text: str, output_path: str, template_target: str | None = None) -> None:
    """Create a .pptx file from text, splitting on blank lines into separate slides.
    Routes to the smart layout engine."""
    blocks = [b.strip() for b in text.split("\n\n") if b.strip()]
    if not blocks:
        blocks = [text]
    
    slide_data = []
    for block in blocks:
        lines = [l for l in block.split("\n") if l.strip()]
        title = lines[0] if lines else "Untitled"
        body = lines[1:] if len(lines) > 1 else []
        slide_data.append({"title": title, "content": body})
        
    create_smart_pptx(slide_data, output_path, template_target)


def pptx_to_docx(path: str, output_path: str) -> None:
    """Convert a .pptx file to .docx, using each slide's text as a section."""
    from docx import Document
    prs = Presentation(path)
    doc = Document()
    for i, slide in enumerate(prs.slides):
        texts = []
        for shape in slide.shapes:
            if shape.has_text_frame:
                for paragraph in shape.text_frame.paragraphs:
                    line = "".join(run.text for run in paragraph.runs)
                    if line:
                        texts.append(line)
        if not texts:
            continue
        doc.add_heading(texts[0], level=1)
        for line in texts[1:]:
            doc.add_paragraph(line)
        if i < len(prs.slides) - 1:
            doc.add_page_break()
    doc.save(output_path)


def docx_to_pptx(path: str, output_path: str, template_target: str | None = None) -> None:
    """Convert a .docx file to .pptx using semantic parsing.
    Headings become Slide Titles. Normal text becomes bullet points."""
    from docx import Document
    doc = Document(path)
    slide_data = []
    current_slide = None

    for p in doc.paragraphs:
        text = p.text.strip()
        if not text:
            continue
        
        is_heading = p.style.name.lower().startswith("heading") or p.style.name.lower() == "title"
        
        if is_heading:
            if current_slide:
                slide_data.append(current_slide)
            current_slide = {"title": text, "content": []}
        else:
            if current_slide is None:
                current_slide = {"title": text, "content": []}
            else:
                current_slide["content"].append(text)

    if current_slide:
        slide_data.append(current_slide)

    create_smart_pptx(slide_data, output_path, template_target)


def pdf_to_pptx(path: str, output_path: str, template_target: str | None = None) -> None:
    """Convert a PDF to .pptx, placing each PDF page's extracted text onto its own slide."""
    from pypdf import PdfReader
    reader = PdfReader(path)
    slide_data = []
    
    for i, page in enumerate(reader.pages):
        text = page.extract_text() or ""
        lines = [l for l in text.split("\n") if l.strip()]
        title = f"Page {i + 1}"
        slide_data.append({"title": title, "content": lines})
        
    create_smart_pptx(slide_data, output_path, template_target)


def extract_pptx_notes(path: str) -> list[str]:
    """Extract the speaker notes from every slide in a .pptx file."""
    prs = Presentation(path)
    notes = []
    for slide in prs.slides:
        if slide.has_notes_slide:
            notes.append(slide.notes_slide.notes_text_frame.text)
        else:
            notes.append("")
    return notes


def merge_pptx_files(paths: list[str], output_path: str) -> None:
    """Merge multiple .pptx files' content into one, preserving slide order across files."""
    slide_data = []
    for path in paths:
        source = Presentation(path)
        for slide in source.slides:
            texts = []
            for shape in slide.shapes:
                if shape.has_text_frame:
                    for paragraph in shape.text_frame.paragraphs:
                        line = "".join(run.text for run in paragraph.runs)
                        if line:
                            texts.append(line)
            title = texts[0] if texts else "Untitled"
            body = texts[1:] if len(texts) > 1 else []
            slide_data.append({"title": title, "content": body})
            
    create_smart_pptx(slide_data, output_path)